### ISSUE TITLE
Integration with pyshtools

### ISSUE THREAD

**Issue by MarkWieczorek** [ioshchepkov/pygeoid#7]
I'm starting to think about how to integrate this into pyshtools, and I have a couple minor comments:

1. In `LevelEllipsoid` could you give the option to input geocentric latitude for the various functions like `normal_gravity()`? The way I would like to use this would be to pass a vector of geocentric latitudes that corresponds to one the shtools grids, and output vectors of the normal gravity and geocentric radius. You probably have the conversion functions written somewhere, but it would be a bit more convenient to specify something like `latitude='geocentric'`.

2. It is not clear which function gives the geocentric radius to a specific latitude: Is this `circle_radius()?`, or is that something else, like the distance to the rotation axis?

3. The pyproj package doesn't define ellipsoids for the other planets. One way to do so would be to create a new pyproj ellipsoid using `pyproj.pj_ellps.update`, the other way would be to pass the required keyword args directly to `Ellipsoid`. Could you provide minimal documentation as to what keyword args are necessary for Ellipsoid to function correctly? I am guessing `a`, and then either `rf` or `b`.

4. Similar remark for `LevelEllipsoid`: To use an ellipsoid that is not defined, it is necessary to either update LEVEL_ELLIPSOIDS, or input all the necessary keyword args. Could you add minimal documentation as to what arguments are necessary for this to work? I'm guessing here you only need `gm`, `omega`, `a`, and then either `rf` or `b`.

5. Would you be interested in adding both ellipsoids and level ellipsoids for the other planets? If not, could you perhaps create some kind of method that allows you to update both pyproj.pj_ellps.update and LEVEL_ELLIPSOID externaly? I'm not sure what the best way to do this is. I'm not sure if anyone has defined such an ellipsoid for Venus and Mercury given that they rotate so slowly. For the Moon it is more complicated, because a level ellipsoid should also include the c22 tidal potential. For Mars, I know that there is a paper by Ardalan et al. (2010). I'd be happy to help out with finding the numbers later.

**Comment by ioshchepkov** [comment]
1. Yes, agree. Sometimes it is more convinient to specify the latitude inside the method. I will think about it, because I see one difficulty as I want to use three coordinate systems at once: geocentric, geodetic and ellipsoidal. 

2. It is `Ellipsoid.polar_equation()` which gives you the distance from the origin to the surface of the ellipsoid dependend on the geocentric latitude. And indeed `circle_radius()` gives you the distance to the rotation axis.

3. Basically, `pyproj` allows you to initialize the class with almost any combination of the geometrical parameters, but, yes, I agree, documenation is needed.

4. I agree too, will do this. Now you can define `GM`, `omega`, `a` and `f` or `J2`. I'm planning to add `U0=W0` value, so only physical parameters (`GM`, `omega`, `J2` and `W0`) will be needed to define the ellipsoid and the remaining parameters can be calculated based on the Somigliana-Pizzetti theory.

5. I see no general problems to add new numerical data, in fact, I'm quite interested in the planetary parameters too, especially for my teaching courses.

**Comment by leouieda** [comment]
Hi @ioshchepkov great work on this package! I've been chatting with @MarkWieczorek recently because the 3 of us have a lot of repeated functionality in our software. I'd been working on something similar in [Harmonica](https://www.fatiando.org/harmonica/dev/index.html). It would be great we could strip out the repeated functionality into a package we can all share.

To organize my thoughts on this, I started [Boule](https://www.fatiando.org/boule/dev) and moved the ellipsoid related code from Harmonica there. That is the part that has the most overlap with pygeoid and shtools.

What is the scope of pygeoid? If your goal is to have more than just the ellipsoid and normal gravity (which you already have), would you consider merging some of the code into Boule so the 3 of us can use it as a dependency?

If we can get a decent amount of functionality in there, I'd be interested in making a [JOSS](https://joss.theoj.org) paper about it at some point.

**Comment by ioshchepkov** [comment]
Hi @leouieda!  The main intention for PyGeoid is to realize common algorithms for physical geodesy. In particular, for local geoid/quasigeoid computations, mainly from gravity anomalies.   I don't know whether it fits with the Harmonica's idea, which looks more like geophysical software. Of course, there are a lot of similarities. In particular, I'm very excited about topography effects in Harmonica and hope to use them in the very near future.

As for Ellipsoid part, yes, I think it is possible to include it in the Boule, but I will be able to do that no early than mid January. 

There are a lot of things, that I would like to include in the ellipsoid-only related software. The theory is very well developed, but poorly present in the current software.

**Comment by leouieda** [comment]
> In particular, for local geoid/quasigeoid computations, mainly from gravity anomalies. I don't know whether it fits with the Harmonica's idea, which looks more like geophysical software.

@ioshchepkov yep, Harmonica is more geophysical so there shouldn't be that much overlap there. But I'll keep an eye on pygeoid just in case there is something else we can share :)

> There are a lot of things, that I would like to include in the ellipsoid-only related software. The theory is very well developed, but poorly present in the current software.

I agree! Everyone seems to be stuck on the Somigliana equation as if we were all still looking up cosines in printed tables.

> As for Ellipsoid part, yes, I think it is possible to include it in the Boule, but I will be able to do that no early than mid January.

I only had time to really work on this now. I moved the Harmonica code to Boule and just pushed a new release. The package is pip and conda installable now and has some basic functionality. I included a Mars ellipsoid as a proof of concept as well.

I opened a few issues on the repository but there is a lot in pygeoid that isn't represented there yet (all the pyproj stuff, for one). 

@MarkWieczorek when you have some time, take a look and see if this is something that could be used in shtools (let me know if there are any changes that need to be made for that to happen).

**Comment by MarkWieczorek** [comment]
Looks good to me. You might want to fix the problem when the flattening is zero, but that's about all I see. Though the flattening is never really zero, it is often treated as such in geophysics when dealing with things like Mercury, Venus, and the Moon, which are either slow rotators or are so irregular in shape that the concept of a flattening isn't too useful. I'm thinking of redoing the planetary constants interface in ~6 months, so I'll look at this more then.

**Comment by leouieda** [comment]
Thanks for the input! I'll see if I can carve out some time to implement the reference Sphere to fix the 0 flattening problem.
